Sprint1/step2
LizaPadawan/react-burgers pull request #2
Opened 2023-02-12 21:28 UTC by LizaPadawan

Sprint1, step 2

2023-02-13 07:21 UTC, andryxxa93 requested changes
Проделана большая работа! Вы хорошо разобрались с функциональными компонентами и правильно используете useEffect.

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Элементы хедера должны быть ссылками

- При запуске проекта происходит ошибка. Рекомендую добавить проверку на наличие данных, если их нет, то не возвращать из компонента ничего. 
<img width="1440" alt="Снимок экрана 2023-02-13 в 10 11 24" src="https://user-images.githubusercontent.com/60173362/218394144-f7e818eb-eb26-4180-a1ae-c3bde3401bdc.png">

- У верхней и нижней булки не должно быть иконок перемещения. 

- У многих компонентов не хватает `propTypes`

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-02-13 07:21 UTC, andryxxa93 commented on src/components/app-header/app-header.js
> +                        <div className={appHeaderStyles.navigation_link_constructor}>
**Надо исправить**

Оберните иконку и текст в ссылку в шапке в ссылку `<a href="#">`

Например
```
<a href="#" class="......">
   <BurgerIcon type="primary" /> Конструктор
</a>
```
В следующих спринтах вместо ссылки будет компонент Link из библиотеки react router, а пока сделайте просто ссылкой

2023-02-13 07:21 UTC, andryxxa93 commented on src/App.tsx
> +async function getDataJson(url : string, callback : any) {
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-02-13 07:21 UTC, andryxxa93 commented on src/App.tsx
> +  //console.log("getDataJson",url);
**Можно улучшить**
Ненужный код лучше удалять

2023-02-13 07:21 UTC, andryxxa93 commented on src/utils/data.json
> +[
**Можно лучше**
Файл больше не нужен - его можно удалить

2023-02-13 07:21 UTC, andryxxa93 commented on src/components/modal/modal.js
> +      window.removeEventListener('keydown', handleEsc);
**Отлично!**
Вы сделали отписку от слушателя, это позволит избежать утечек памяти.

2023-02-13 07:21 UTC, andryxxa93 commented on src/components/modal/modal.js
> +  let modal = document.getElementById(props.modalId);
**Можно лучше**

**здесь и далее в других местах** если переменная не перезаписывается её нужно объявлять как `const`, это помогает понять другим разработчикам, как мы будем использовать переменную, будем ли мы в коде перезаписывать её значение.
Так же стоит помнить, что добавление элемента в массив или изменение свойства объект не являются перезаписью самой переменной, а только изменяют его внутренне состояние и такие переменные так же объявляются как const

2023-02-13 07:21 UTC, andryxxa93 commented on src/components/modal-overlay/modal-overlay.js
> +export default ModalOverlay;
**Надо испарвить**

для этого компонента так же нужно описать PropTypes

2023-02-13 07:21 UTC, andryxxa93 commented on src/App.tsx
> +  console.log("App");
**Можно улучшить**
Console.log нужен только для процесса разработки, перед сдачей проекта его нужно удалять, иначе она будет загружать консоль ненужной, а возможно и приватной информацией. А ошибку лучше записывать в state и показывать пользователю, чтобы он понимал, что происходит.

2023-02-13 17:46 UTC, LizaPadawan commented
Исправлены все “нужно исправить” пункты по ревью:
Элементы header сделаны как ссылки
2) Чтобы избавиться от warning, добавлена проверка на наличие данных data и keys.
3) У верхней и нижней булки убраны иконки перемещения.
4) Ко всем компонентам описаны PropTypes.

То, что “нужно улучшить” - спасибо большое за все замечания, исправлю к следующему ревью.

2023-02-14 06:44 UTC, andryxxa93 requested changes
Последнее замечание и ваша работа будет принята.
- В компонентах которые принимают ингредиенты необходимо полностью расписать типизацию полей через propTypes. Рекомендую объявить константу с типизацией в отдельном файле и оттуда импортировать всюду куда нужно. Выглядеть это должно как-то так 
```
const ingredientPropTypes = PropTypes.shape({
  _id: PropTypes.string.isRequired,
  name: PropTypes.string.isRequired,
  type: PropTypes.string.isRequired,
   ...
});
```

2023-02-14 06:44 UTC, andryxxa93 commented on src/App.tsx
> +import React, {useEffect, useState} from 'react';
**Можно лучше**
Следует поменять расширение у всех `tsx` файлов на `jsx`. Сейчас `typescript` не используется и могут возникать ошибки с типизацией, в будущем будет спринт посвященный `typescript`

2023-02-14 06:44 UTC, andryxxa93 commented on src/components/app-header/app-header.js
> +                {/* <div className={appHeaderStyles.content}>
**Можно улучшить**
Ненужный код лучше удалять

2023-02-14 08:40 UTC, LizaPadawan commented
Добавлен файл с ingredientPropTypes, импортирован в нужные места

2023-02-14 09:22 UTC, andryxxa93 approved these changes
Супер! Все замечания учтены, вы отлично поработали. Ваша работа принята.
Желаю удачного продолжения обучения!

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

2023-02-14 09:22 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.js
> +        // <>
**Можно улучшить**
Ненужный код лучше удалять

2023-02-14 09:22 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.js
>      data: PropTypes.array.isRequired,
**Можно лучше**
Вот тут необходимо сделать так - 
`    data: PropTypes.arrayOf(ingredientPropTypes).isRequired,`

2023-02-14 09:22 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.js
> +        <div  style={{display:'flex', justifyContent:'center'}}>
**Можно улучшить**
Когда идёт рендер списка необходимо добавлять атрибут `key` каждому элементу.
https://ru.reactjs.org/docs/lists-and-keys.html

2023-02-17 09:56 UTC, merged