Sprint2/step1
LizaPadawan/react-burgers pull request #3
Opened 2023-02-17 13:37 UTC by LizaPadawan

Данные в BurgerIngredients и BurgerConstructor передаются через Context,
отображается сумма заказа,
отображается номер заказа в модальном окне

2023-02-17 15:27 UTC, andryxxa93 requested changes
Отличная работа! 
Что понравилось:
- Context используется верно, в него обернуты только те компоненты, которые будут его использовать
- Есть подсчет стоимости заказа 
- У запросов есть проверка успешности

Однако есть пару замечаний, которые необходимо исправить:

- Не работает закрытие модалки по нажатию на крестик.
- По дизайну у подложки полупрозрачный фон.
- Необходимо, чтобы запрос на номер заказа уходил по нажатию на кнопки "Оформить заказ" а не по рендеру модального окна.
- Необходимо удалить файл `App.test.tsx` - он не нужен в проекте.
- В консоли есть ошибка из-за того, что в IngredientDetails не передается параметр key в рендере списка.
<img width="1440" alt="Снимок экрана 2023-02-17 в 18 22 59" src="https://user-images.githubusercontent.com/60173362/219694737-2c83fcea-7ef4-4dc9-9bdd-dade0243009d.png">

https://ru.reactjs.org/docs/lists-and-keys.html


В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-02-17 15:27 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.js
> +const OrderDetails = (props) => {
**Можно улучшить**
Здесь и в коде других компонентов, лучше не писать каждый раз `props`, а использовать деструктуризацию, достав все необходимые данные из пропсов один раз. Это сделает код более понятным. https://learn.javascript.ru/destructuring#destrukturizatsiya-obekta

2023-02-17 15:27 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.js
> +        []
**Необходимо исправить**
функция `sendOrder` должна срабатывать при нажатии на кнопку "Оформить заказ" а не при рендере модального окна. Хорошо так же по возможности не показывать модальное окно если произошла ошибка, в нынешнем виде модальное окно будет открываться всегда. Так же рекомендую вынести функцию `sendOrder` в отдельный файл.

2023-02-17 15:27 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.js
> +    const summ = data.find(item => item.type == 'bun').price * 2 + data.filter(item => item.type !== 'bun').map((item) => item.price).reduce((a, b) => { return a + b; });
**Можно лучше**
Сложные операции желательно оборачивать в хук `useMemo` чтобы избежать ненужных выполнений. 
https://ru.reactjs.org/docs/hooks-reference.html#usememo

2023-02-17 15:27 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.js
> +    //const { data } = props;
**Можно улучшить**
Ненужный код лучше удалять

2023-02-17 15:27 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.js
> +        if (response.ok) {
**Можно лучше**
У вас в проекте уже есть функция для проверки ответа сервера - не стоит дублировать код.

2023-02-20 07:57 UTC, LizaPadawan commented
Исправлены ошибки в модальном окне, добавлен order-context для правильного рендеринга заказа, ошибки из консоли.

2023-02-20 08:27 UTC, andryxxa93 reviewed
Супер! Вы отлично поработали. Работа принята, удачного вам продолжения обучения!

2023-02-20 08:27 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.js
> +  //data: PropTypes.array.isRequired,
**Можно улучшить**
Ненужный код лучше удалять. Типизация `data` здесь уже не понадобится, на следующих спринтах будет подключение `Redux`, так что можете смело удалять.

2023-03-09 17:30 UTC, merged