Sprint2/step2
LizaPadawan/react-burgers pull request #4
Opened 2023-02-25 23:19 UTC by LizaPadawan

1) Работа переведена в глобальное состояние с помощью redux
2) Реализовано создание бугера с помощью Drag-and-Drop
3) По скроллу меняется выделенный заголовок табов

2023-02-26 05:16 UTC, andryxxa93 requested changes
Здравствуйте! Проделана огромная работа 👍 
Что понравилось:
- Созданы статичные селекторы
- `Dnd` работает отлично
- Созданы утилитарные функции для запросов

Что необходимо исправить:
- [x] Чтобы пользователь понимал как добавить ингредиенты в конструктор - для пустого конструктора добавьте надпись "Перенесите ингредиенты сюда".
- [x] После оформления заказа конструктор необходимо очищаться, что юзер не делал это сам.
- [x] Для каждого экшена, который связан с запросом к Api должен быть создан усилитель. Для таких экшенов необходимо описать тип _REQUEST, тип _SUCCESS, _ERROR
- [x] Разделите редьюсер и экшен на несколько по доменным областям (см подробнее комментарий к pull-request).
- [x] В некоторых местах вы удалили propTypes - хотя пропсы у компонента по-прежнему есть и используются. Например у `ConstructorBunElement` и `IngredientCard`. Проверьте во всем проекте.
- [ ] Если при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента необходимо приводить к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов.

**Можно лучше**
- В проекте много не используемого и закоментированого кода - его стоит удалять.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-02-26 05:16 UTC, andryxxa93 commented on src/App.js
> +      // <DataContext.Provider value={fetchedData.data}>
**Можно улучшить**
Ненужный код лучше удалять

2023-02-26 05:16 UTC, andryxxa93 commented on src/services/action-creator.js
> +export const actionCreators = {
**Надо исправить**
следует разделить экшены по файлам, на нас есть несколько задач (доменных областей) не связанных между собой - загрузка ингредиентов, оформление заказа, работа конструктор. Лучше, что бы экшены относящиеся к решению каждой были описаны в своем файле, т.к. приложение со времени будет развиваться, будет добавлять новый функционал и плохо, если придется все экшены описывать в одном файле, он будет слишком большой

В текущем приложении можно разделить на следующие файлы:
- загрузка данных ингредиентов
- работа конструктора
- открытие ингредиента в попапе
- оформление заказа

2023-02-26 05:16 UTC, andryxxa93 commented on src/services/reducer.js
> +import { initialState } from "./initial-state" ;
**Надо исправить**

со временем приложение будет разрастаться, появится новый функционал, если все будет в одном рельюсере он станет слишком большим, разделите один большой редьюсер на несколько, обрабатывающие данные одной предметной области (одного "домена"), например

- загрузка данных ингредиентов
- отправка заказа
- работа конструктора
- открытие модального окна ингредиента

Для объединения редьюсеров используйте combineReducers
https://redux.js.org/api/combinereducers

2023-02-26 05:16 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.js
> +  let count = constructorElements.filter(item => item._id == props._id).length;
**Можно лучше**
Сложные операции желательно оборачивать в хук `useMemo` чтобы избежать ненужных выполнений. 
https://ru.reactjs.org/docs/hooks-reference.html#usememo

2023-02-26 05:16 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.js
>  function IngredientCard(props){
**Можно лучше**
Лучше для каждого компонента создавать отдельный файл чтобы разгрузить текущий и не делать его слишком большим и запутанным.

2023-02-27 11:50 UTC, LizaPadawan commented
Добрый день! Отправляю исправленный вариант на проверку, но появилась проблема - перестал отображаться номер заказа. Но логам до редьюсера все идет правильно, но потом selector возвращает пустое значение. Помогите, пожалуйста, разобраться

2023-02-27 14:13 UTC, LizaPadawan commented
Номер заказа теперь отображается! Нужно было поменять местами dispatch. Но почему не работал старый вариант, непонятно. Если вы знаете причину, напишите, пожалуйста :)

2023-02-27 20:55 UTC, andryxxa93 approved these changes
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

**Можно лучше**
- Проблема в том, что вы очищаете номер заказа когда диспатчиться экшен OPEN_MODAL. Это хорошо видно в redux devtools - крайне рекомендую начать пользоваться этим инструментом, в проекте его не просто так подключили :smiley: .
Т.е. вам следует поправить редьюсер модального окна. 
<img width="1440" alt="Снимок экрана 2023-02-27 в 23 49 08" src="https://user-images.githubusercontent.com/60173362/221682523-2c5f6dc5-91da-49c0-a262-1a2e2a0e2916.png">

Расширение для браузера - https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd. Чтобы его открыть следует открыть консоль разработчика  F12 и найти вкладку Redux. 

- Если конструктор пустой, то лучше скрывать или дизейблить кнопку "Оформить заказ" - иначе сейчас возникает ошибка.

2023-03-09 17:30 UTC, merged