Sprint3 step1
LizaPadawan/react-burgers pull request #5
Opened 2023-03-18 20:41 UTC by LizaPadawan

2023-03-19 04:27 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Теперь у вас есть роутинг;
- Есть регистрация и авторизация;

### **Но есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/7XvkHu0YWA6zPA> - по макету, тут кастомный скролл, а также не должно быть скролла по горизонтали.

- В файлах, где содержится `jsx`, нужно поменять расширение с `.js` на `.jsx`;

- В директории `components` должен быть компонент App. Компонент `App`, он также должен быть в папке (как и другие компоненты). Как правило, это основной компонент в React, который выступает в качестве контейнера для всех остальных компонентов;

- Вы должны добавлять в хедер запроса `POST /orders`, токен пользователя `Bearer ...`, чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали);

- В запросе `/orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/XqokoQCJMLAaBg>;

- <https://disk.yandex.com/i/dzO9nFsG9Xhbaw> - по макету, у иконки должен быть фон;

- <https://disk.yandex.com/i/G-dWR-OsWmWaNQ> - по макету, у ссылок нет нижнего подчёркивания;

- <https://disk.yandex.com/i/cKi1kUwBtYnBww> - нужно поправить модальное окно: выровнять контент, высоту и убрать боковой скролл у страницы;

- Кажется, вы перепутали поля - <https://disk.yandex.com/i/yrLTacYa_HLghg>;

- По чек-листу, требуется реализовать:

  - При клике по ингредиенту происходит переход на маршрут /ingredients/:id и открывается модальное окно с описанием ингредиента. При прямом переходе на этот маршрут открывается страница с информацией об ингредиенте. Прошу обратить внимание на запрос `GET - /ingredients` (получение ингредиентов), его лучше делать всего 1 раз, в компоненте `app`;

  - Роуты `/login` и `/register`, `/forgot-password` и `/reset-password` недоступны авторизованным пользователям;

  - `/reset-password` доступен неавторизованным пользователям только после посещения маршрута `/forgot-password` и ввода адреса электронной почты для восстановления пароля;

  - При клике на «История заказов» происходит переход на экран `/profile/orders`, ссылка «История заказов» становится активной, экран `/profile/orders` пока отображается пустым;

  - Роуты `/profile` и все вложенные в `/profile` маршруты доступны только авторизованным пользователям, т. е. защищены HOC-компонентом ProtectedRoute.

  - При попытке неавторизованных пользователей перейти на защищённые роуты происходит редирект на `/login`. После успешной авторизации происходит переадресация на тот маршрут, к которому пользователь не получил доступ ранее.

  - Если пользователь отредактировал данные в форме, то появляются кнопки "Отмена" и "Сохранить".
    При нажатии кнопки "Сохранить" на странице профиля пользователя отправляется соответствующий запрос к Api содержащий измененные данные.
    При нажатии кнопки "Отмена" значения полей формы возвращаются в состояние до редактирования, а кнопки "Отмена" и "Сохранить" скрываются.
    А также в поле `имя` должны подтягиваться данные с профиля;
    <https://disk.yandex.com/i/oncaCq1WY2oFmg>

  - Вам нужно проверить запросы, некоторые их них (`POST /login`, `POST /order`, `PATCH /user`) должны посылать `accessToken`. При запросах использующих accessToken проверяется ответ сервера. Если время жизни токена истекло, то выполняется запрос обновления токена и повторяется запрос, который не был выполнен успешно.

- Вы должны вешать обработчик на событие `onSubmit` элемента `form`, а не на кнопку;

### **Сделает код лучше:**

- оборачивать в React.Fragment требуется, только если в компонент содержит несколько невложенных блоков, например

  ```js
  <>
    <div>.....</div>
    <div>.....</div>
  </>
  ```

  <https://ru.reactjs.org/docs/fragments.html>

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-03-19 04:27 UTC, ArslanMustafin commented on src/pages/forgot-password/forgot-password-page.js
> +      <>
**Можно лучше:**

Здесь и в других местах.

эта обёртка `<>` лишняя, оборачивать в React.Fragment требуется, только если в компонент содержит несколько невложенных блоков, например

```js
<>
  <div>.....</div>
  <div>.....</div>
</>

```

[https://ru.reactjs.org/docs/fragments.html](https://ru.reactjs.org/docs/fragments.html)

2023-03-19 04:27 UTC, ArslanMustafin commented on src/pages/forgot-password/forgot-password-page.js
> +          onClick={() => {dispatch(forgotPasswordRequest(form, navigate))}}
**Надо исправить:**

Вы должны вешать обработчик на событие `onSubmit` элемента `form`, а не на кнопку.

2023-03-19 04:27 UTC, ArslanMustafin commented on src/pages/login/login-page.js
> +          onClick={() => {dispatch(login(form, navigate))}}
**Надо исправить:**

Вы должны вешать обработчик на событие `onSubmit` элемента `form`, а не на кнопку.

2023-03-19 04:27 UTC, ArslanMustafin commented on src/pages/register/register-page.js
> +          onClick={() => {dispatch(register(form, navigate))}}
**Надо исправить:**

Вы должны вешать обработчик на событие `onSubmit` элемента `form`, а не на кнопку.

2023-03-19 04:27 UTC, ArslanMustafin commented on src/pages/reset-password/reset-password-page.js
> +          onClick={() => dispatch(resetPasswordRequest(form, navigate))}
**Надо исправить:**

Вы должны вешать обработчик на событие `onSubmit` элемента `form`, а не на кнопку.

2023-03-19 04:27 UTC, ArslanDev666 commented on src/pages/forgot-password/forgot-password-page.js
> +  const [form, setForm] = useState({ email: "" });
**Можно лучше:**

Можно сделать универсальный кастомный хук для контроля любого количества инпутов в любых формах:

```js
export function useForm(inputValues) {
  const [values, setValues] = useState(inputValues);

  const handleChange = event => {
    const { value, name } = event.target;
    setValues({ ...values, [name]: value });
  };
  return { values, handleChange, setValues };
}
```

Этот код помещают в отдельный файл useForm.js в папке hooks и импортируют функцию туда, где нужно контролировать инпуты

И Вам не нужно будет теперь вручную создавать функции обработки инпутов и т д. Все будет в одной строчке кода:

```js
const { values, handleChange, setValues } = useForm({...});
```

2023-03-19 04:27 UTC, ArslanDev666 commented on src/services/thunk.js
> +    }
**Можно лучше:**

Немного не понятна ваша логика, зачем тут делать диспатч при не удачном запросе:?

2023-03-19 04:27 UTC, ArslanDev666 commented on src/services/thunk.js
> +        getDataJson('https://norma.nomoreparties.space/api/ingredients', setIngredients, dispatch);
**Надо исправить:**

здесь и далее.

вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в константу в отдельный файл, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/ingredients`

2023-03-19 04:27 UTC, ArslanDev666 commented on src/services/thunk.js
> +const sendForm = (form, url) => {
**Можно лучше:**

такие функции лучше вынести наверх, или в файл утилит

2023-03-19 04:27 UTC, ArslanDev666 commented on src/services/thunk.js
> +    }
**Можно лучше:**

проверка ответа сервера и преобразование из json дублируется в нескольких местах, нужно вынести в отдельную функцию:

```js
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

2023-03-21 04:13 UTC, LizaPadawan commented
Здравствуйте! Исправлены все "нужно исправить". Есть проблема, что когда пользователь зарегистрирован и начинает заполнять конструктор, стираются данные userReducer, а они нужны для роутинга. В редьюсере искала ошибку, в том числе полностью переписывала - проблема остается. У меня не хватает знаний, где еще можно найти эту проблему. Не подскажете, пожалуйста, в какую сторону думать\как исправить?

2023-03-21 04:36 UTC, ArslanDev666 commented
> когда

Доброго времени суток, вот тут нужно указывать `state`, а не `initialState`: https://disk.yandex.com/i/bRb79xZl_mhzCw. Нужно помнить, что у вас всего 1 большой редьюсер)) а не несколько маленьких

2023-03-21 09:51 UTC, LizaPadawan commented
Спасибо вам большое! Исправила initialState, селекторы, редьюсеры - все заработало.

2023-03-21 15:57 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Практически все замечания были исправлены;

### **Но все ещё есть несколько замечаний, которые нужно исправить:**

- При отправке заказа, в случае, если пользователь не авторизирован., вы должны отправлять его на авторизацию. <https://disk.yandex.com/i/3mAIc5f_T5hYgQ>;

- Вы должны добавлять в хедер запроса `POST /orders`, токен пользователя `Bearer ...`, чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали); У вас есть такой запрос, но используете вы почему-то другой);

- <https://disk.yandex.com/i/w_dH2Mw5w8DdHg> - добавьте чуток отступ между названием и параметрами;

- При клике на «История заказов» происходит переход на экран `/profile/orders`, ссылка «История заказов» становится активной, экран `/profile/orders` пока отображается пустым; У вас открывается новая страница, а нужно чтобы ссылка стала активной и поменялся контент (P.S. не забудьте поменять описание). <https://disk.yandex.com/i/eh0YhUSm8dbQiw>;

2023-03-21 15:57 UTC, ArslanDev666 commented on src/pages/forgot-password/forgot-password-page.jsx
> +      onSubmit={(e) => { e.preventDefault(); dispatch(forgotPasswordRequest(form, navigate)) }}
**Можно лучше:**

здесь и в других похожих местах.

Лучше вынести обработчик событий в отдельную функцию.

2023-03-22 12:16 UTC, LizaPadawan commented
Исправлены все "нужно исправить"

2023-03-22 15:09 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

### **Сделает код лучше:**

- При отправке заказа, в случае, если пользователь не авторизирован, вы должны отправлять его на авторизацию. <https://disk.yandex.com/i/3mAIc5f_T5hYgQ>;

- Нужно запретить пользователю отправлять заказ, если он не выбрал булки. <https://disk.yandex.com/i/qbFMDbYbOufrqg>;

2023-03-29 08:08 UTC, merged